### PR TITLE
[close #159] remove cli unused command options

### LINKED ISSUE #159: cdc: There are some useless command options in cli
### 1. Describe the bug

There are some useless commands in cli

### 2. Minimal reproduce step (Required)
./tikv-cdc cli create help

### 3. What did you see instead (Required)
image

### 4. What did you expect to see? (Required)
image

### 5. What is your migration tool and TiKV version? (Required)

- TiKV CDC:

### PR DESCRIPTION
**Pull request by zeminzhou**
Signed-off-by: zeminzhou <zhouzemin@pingcap.com>

### What problem does this PR solve?
see issuse #159 

Issue Number: close #159

Problem Description: **TBD**
There are some useless commands in cli

### What is changed and how does it work?
remove them

### Code changes

- Has exported function/method change
- Has exported variable/fields change

### Check List for Tests

This PR has been tested by at least one of the following methods:
- Unit test
- Manual test (add detailed scripts or steps below)

### CODE REVIEW

File: cdc/pkg/cmd/cli/cli_changefeed_create.go [hunk 1]
```diff
@@ -379,17 +330,6 @@ func (o *createChangefeedOptions) run(ctx context.Context, cmd *cobra.Command) e
 		return err
 	}
 
-	if !o.commonChangefeedOptions.noConfirm {
-		currentPhysical, _, err := o.pdClient.GetTS(ctx)
-		if err != nil {
-			return err
-		}
-
-		if err := confirmLargeDataGap(cmd, currentPhysical, o.startTs); err != nil {
```
Comment (pingyu) [inline cdc/pkg/cmd/cli/cli_changefeed_create.go:388]: The `confirmLargeDataGap` may be useful for us. It is used to prevent OOM.. Suggest to keep it.

File: cdc/pkg/cmd/cli/cli_changefeed_update.go [hunk 2]
```diff
@@ -113,19 +112,6 @@ func (o *updateChangefeedOptions) run(cmd *cobra.Command) error {
 		cmd.Printf("%+v\n", change)
 	}
 
-	if !o.commonChangefeedOptions.noConfirm {
```
Comment (pingyu) [inline cdc/pkg/cmd/cli/cli_changefeed_update.go:116]: The `noConfirm` will suppress the confirm prompt, will be useful for updating changefeed in scripts. Suggest to keep it.

File: cdc/pkg/cmd/cli/cli_changefeed_create.go [hunk 3]
```diff
@@ -70,33 +63,16 @@ func (o *changefeedCommonOptions) addFlags(cmd *cobra.Command) {
 		return
 	}
 
-	cmd.PersistentFlags().BoolVar(&o.noConfirm, "no-confirm", false, "Don't ask user whether to ignore ineligible table")
 	cmd.PersistentFlags().Uint64Var(&o.targetTs, "target-ts", 0, "Target ts of changefeed")
 	cmd.PersistentFlags().StringVar(&o.sinkURI, "sink-uri", "", "sink uri")
-	cmd.PersistentFlags().StringVar(&o.configFile, "config", "", "Path of the configuration file")
```
Comment (haojinming) [inline cdc/pkg/cmd/cli/cli_changefeed_create.go:76]: Maybe keep the `configFile` option but mark it as hiden.

File: cdc/pkg/cmd/cli/cli_changefeed_create.go [hunk 4]
```diff
@@ -64,7 +64,7 @@ func (o *changefeedCommonOptions) addFlags(cmd *cobra.Command) {
 		return
 	}
 
-	cmd.PersistentFlags().BoolVar(&o.noConfirm, "no-confirm", false, "Don't ask user whether to ignore ineligible table")
+	cmd.PersistentFlags().BoolVar(&o.noConfirm, "no-confirm", false, "Don't ask user whether to continue creating changefeed when replicate lag tis too large")
```
Comment (pingyu) [inline cdc/pkg/cmd/cli/cli_changefeed_create.go:67]:
```suggestion
	cmd.PersistentFlags().BoolVar(&o.noConfirm, "no-confirm", false, "Don't ask user to confirm warnings")
```

Please also change the "no-confirm" argument message for `changefeed resume` (in `cli_changefeed_resume`).

**Review by pingyu — COMMENTED** [review]
Rest LGTM.

**Review by pingyu — APPROVED** [review]
LGTM~

**Review by haojinming — APPROVED** [review]
