### PR TITLE
[close #189] Br checksum use rawkv client interface

### LINKED ISSUE #189: [BR] Use client-go checksum interface instead of sending request directly
### 1. Describe the bug

Use client-go checksum interface instead of send request directly

### 3. What did you see instead (Required)

Use client-go checksum interface instead of send request directly

### 5. What is your migration tool and TiKV version? (Required)

- TiKV BR:

### PR DESCRIPTION
**Pull request by haojinming**
### What problem does this PR solve?

Issue Number: close #189 

Problem Description: 

### What is changed and how does it work?
Use client-go checksum interface instead of sending request directly. It's more stable and can handle more region error caes.

### Code changes

- Has exported function/method change

### Check List for Tests

This PR has been tested by at least one of the following methods:
- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

### Side effects

- No side effects

### Related changes

- No related changes

### CODE REVIEW

File: br/pkg/checksum/executor_test.go [hunk 1]
```diff
@@ -15,56 +15,167 @@
...
-	mockClient := &mockPdCLient{}
-	err := NewExecutor([]byte(""), []byte(""), kvrpcpb.APIVersion_V2, mockClient, 1).
-		Execute(ctx, stubChecksum, StorageChecksumCommand, nil)
-	require.Equal(t, err, nil)
-}*/
+func (c *TestChecksumClient) Close() error {
+	return nil
+}
+
+func GenerateTestData(keyIdx int64) (key, value string) {
```
Comment (pingyu) [inline br/pkg/checksum/executor_test.go:93]: Nit: suggest to be `generateTestData` if it is used in this module only. Or move to a common module if it will be used by other test cases. The same to following functions.

File: br/pkg/checksum/executor_test.go [hunk 2]
```diff
@@ -15,56 +15,167 @@
...
+		keyRanges:      keyRanges,
+		apiVersion:     kvrpcpb.APIVersion_V1,
+		checksumClient: &client,
+		concurrency:    5,
+	}
+	rawChecksum, err := client.Checksum(ctx, []byte("a"), []byte("z"))
+	require.Nil(t, err)
+	callbakcCnt := int64(0)
+	callback := func(unit backup.ProgressUnit) {
+		callbakcCnt += 1
```
Comment (pingyu) [inline br/pkg/checksum/executor_test.go:139]: Should be atomic. The `callback` is invoked concurrently in goroutine.

File: br/pkg/checksum/executor_test.go [hunk 3]
```diff
@@ -15,56 +15,167 @@
...
-	start, end = adjustRegionRange([]byte("a"), []byte("z"), []byte(""), []byte(""))
-	require.Equal(t, string(start), "a")
-	require.Equal(t, string(end), "z")
-	start, end = adjustRegionRange([]byte("a"), []byte(""), []byte(""), []byte("z"))
-	require.Equal(t, string(start), "a")
-	require.Equal(t, string(end), "z")
-	start, end = adjustRegionRange([]byte(""), []byte("z"), []byte("a"), []byte(""))
-	require.Equal(t, string(start), "a")
-	require.Equal(t, string(end), "z")
+func TestChecksumAPIV1(t *testing.T) {
```
Comment (pingyu) [inline br/pkg/checksum/executor_test.go:110]: It's testing for both API V1 & V2 ?

File: br/pkg/checksum/executor.go [hunk 4]
```diff
@@ -22,77 +22,55 @@ import (
...
-		retStart = regionStart
-	}
-	retEnd := end
-	if len(retEnd) == 0 || (len(regionEnd) != 0 && string(retEnd) > string(regionEnd)) {
-		retEnd = regionEnd
+func NewExecutor(ctx context.Context, keyRanges []*utils.KeyRange, pdAddrs []string, apiVersion kvrpcpb.APIVersion,
+	concurrency uint) (*Executor, error) {
+	rawkvClient, err := rawkv.NewClientWithOpts(ctx, pdAddrs, rawkv.WithAPIVersion(apiVersion))
+	if err != nil {
+		return nil, nil
```
[the remark this answers is not in the document]
Comment (haojinming) [reply br/pkg/checksum/executor.go:66]: thanks, fixed.

File: br/pkg/checksum/executor_test.go (hunk 3 above)
Comment (haojinming) [reply br/pkg/checksum/executor_test.go:110]: yes, the test case name is changed.

**Review by pingyu — APPROVED** [review]
LGTM~

**Comment by pingyu** [comment]
@zeminzhou PTAL~

**Review by zeminzhou — APPROVED** [review]
