### PR TITLE
[fix #241] fix flow control

### LINKED ISSUE #241: cdc: OOM happend when create 20 changefeed
### 1. Describe the bug
OOM happend when create 20 changefeed

### 2. Minimal reproduce step (Required)
1. start up upstream tikv & tikv-cdc & downstream tikv;
2. craete 20 chagnefeeds;
3. input data into upstream tikv;
4. OOM happened

### 3. What did you see instead (Required)
1. OOM happened

### 4. What did you expect to see? (Required)
1. No errer happened

### 5. What is your migration tool and TiKV version? (Required)

- TiKV CDC:

### PR DESCRIPTION
**Pull request by zeminzhou**
Signed-off-by: zeminzhou <zhouzemin@pingcap.com>

### What problem does this PR solve?
Fix flow control

Issue Number: close #241

Problem Description: **TBD**

### What is changed and how does it work?
Fix flow control

### Code changes

- Has exported function/method change

### Check List for Tests

This PR has been tested by at least one of the following methods:
- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

### CODE REVIEW

**Comment by zeminzhou** [comment]
@pingyu @haojinming

File: cdc/cdc/processor/pipeline/sorter.go [hunk 1]
```diff
@@ -151,6 +151,30 @@ func (n *sorterNode) StartActorNode(ctx pipeline.NodeContext, eg *errgroup.Group
...
+						}
+						return nil
+					})
+					if err != nil {
+						if cerror.ErrFlowControllerAborted.Equal(err) {
+							log.Info("flow control cancelled for keyspan",
+								zap.Uint64("keyspanID", n.keyspanID),
+								zap.String("keyspanName", n.keyspanName))
+						} else {
+							ctx.Throw(err)
```
Comment (haojinming) [inline cdc/cdc/processor/pipeline/sorter.go:174]: Does this cause panic?

File: cdc/cdc/processor/pipeline/sorter.go [hunk 2]
```diff
@@ -188,6 +212,7 @@ func (n *sorterNode) TryHandleDataMessage(ctx context.Context, msg pipeline.Mess
 					zap.Uint64("resolvedTs", resolvedTs),
 					zap.Uint64("oldResolvedTs", oldResolvedTs))
 			}
+			atomic.StoreUint64(&n.resolvedTs, rawKV.CRTs)
```
Comment (pingyu) [inline cdc/cdc/processor/pipeline/sorter.go:215]: Why ? The previous `oldResolvedTs := atomic.SwapUint64(&n.resolvedTs, resolvedTs)` should have done the assignment.

File: cdc/cdc/processor/pipeline/sorter.go [hunk 3]
```diff
@@ -151,6 +151,30 @@ func (n *sorterNode) StartActorNode(ctx pipeline.NodeContext, eg *errgroup.Group
 						}
 					}
 
+					// We calculate memory consumption by PolymorphicEvent size.
```
Comment (pingyu) [inline cdc/cdc/processor/pipeline/sorter.go:154]: About `PerKeySpanMemoryQuota`:

1. The default value `10MB` may be too small. `1GB` may be fine.

2. I think we can change the config item name `per-keyspan-memory-quota` to `per-changefeed-memory-quota`, as users have no idea that what `keyspan` is.

3. It would better to default to a proportion of total system memory, for ease of use. Refer to [`MaxMemoryPresure`](https://github.com/tikv/migration/blob/b559233b0f166429b904b8a4390db310a966dacb/cdc/pkg/config/server_config.go#L88). (Not a must in this PR).

**Review by pingyu — COMMENTED** [review]
Suggest to add some test case to verify the consuming & releasing (including integrated & e2e tests). If we miss some release, the `flowController.Consume` will block the data flow.

File: cdc/cdc/processor/pipeline/sorter.go (hunk 1 above)
Comment (zeminzhou) [reply cdc/cdc/processor/pipeline/sorter.go:174]: It does not cause panic, just throws a err to parents ndoes.

File: cdc/cdc/processor/pipeline/sorter.go (hunk 2 above)
Comment (zeminzhou) [reply cdc/cdc/processor/pipeline/sorter.go]: Removed, thanks! PTAL~

File: cdc/cdc/processor/pipeline/sorter.go (hunk 3 above)
Comment (zeminzhou) [reply cdc/cdc/processor/pipeline/sorter.go:154]: Thanks for your suggestion, I do the following:
1. changed `10MB` to `1GB`;
2. changed `per-keyspan-memory-quota` to `per-changefeed-memory-quota`;

File: cdc/cdc/processor/pipeline/sorter.go [hunk 4]
```diff
@@ -151,6 +151,30 @@ func (n *sorterNode) StartActorNode(ctx pipeline.NodeContext, eg *errgroup.Group
...
+					size := uint64(msg.RawKV.ApproximateDataSize())
+					// NOTE we allow the quota to be exceeded if blocking means interrupting a transaction.
+					// Otherwise the pipeline would deadlock.
+					err := n.flowController.Consume(commitTs, size, func() error {
```
Comment (haojinming) [inline cdc/cdc/processor/pipeline/sorter.go:158]: Suggest add a metric to observe the blocking time.

**Comment by zeminzhou** [comment]
image

File: cdc/cdc/processor/pipeline/sorter.go (hunk 4 above)
Comment (zeminzhou) [reply cdc/cdc/processor/pipeline/sorter.go:160]: image
added, thanks! PTAL~

**Review by haojinming — APPROVED** [review]
LGTM

File: cdc/metrics/grafana/tikv-cdc.json [hunk 5]
```diff
@@ -2965,7 +2965,7 @@
           "steppedLine": false,
           "targets": [
             {
-              "expr": "sum(rate(tikv_cdc_processor_table_memory_consumption_sum{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[30s]) / rate(tikv_cdc_processor_table_memory_consumption_count{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[30s])) by (capture)",
+              "expr": "sum(rate(tikv_cdc_processor_changefeed_memory_consumption_sum{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[30s]) / rate(tikv_cdc_processor_changefeed_memory_consumption_count{tidb_cluster=\"$tidb_cluster\", capture=~\"$capture\"}[30s])) by (capture)",
```
Comment (pingyu) [inline cdc/metrics/grafana/tikv-cdc.json:2968]: Please also paste the screenshot of these two metrics.

**Review by pingyu — COMMENTED** [review]
Rest LGTM.

File: cdc/metrics/grafana/tikv-cdc.json (hunk 5 above)
Comment (zeminzhou) [reply cdc/metrics/grafana/tikv-cdc.json:2968]: pasted, PTAL -> https://github.com/tikv/migration/pull/242#issuecomment-1272883940

File: cdc/cdc/processor/pipeline/metrics.go [hunk 6]
```diff
@@ -32,19 +32,28 @@ var (
...
+	changefeedMemoryHistogram = prometheus.NewHistogramVec(
 		prometheus.HistogramOpts{
 			Namespace: "tikv_cdc",
 			Subsystem: "processor",
-			Name:      "keyspan_memory_consumption",
+			Name:      "changefeed_memory_consumption",
 			Help:      "estimated memory consumption for a keyspan after the sorter",
 			Buckets:   prometheus.ExponentialBuckets(1*1024*1024 /* mb */, 2, 10),
 		}, []string{"changefeed", "capture"})
+	flowControllerConsumeHistogram = prometheus.NewHistogramVec(
```
[the remark this answers is not in the document]
Comment (zeminzhou) [reply cdc/cdc/processor/pipeline/metrics.go]: added, thanks! PTAL~

**Review by pingyu — APPROVED** [review]
LGTM~
