### PR TITLE
[close #108] Br debug checksum cmd

### LINKED ISSUE #108: [TiKV-BR] checksum may mismatch when enabling ttl
### 1. Describe the bug
Some KV data with ttl expired, when doing BR( backup or restore )
The checksum will mismatch.

### 2. Minimal reproduce step (Required)
1. enable ttl
2. set KV with a short ttl duration
3. BR costs more time than KV ttl.

### 3. What did you see instead (Required)
Mismatch.

### 4. What did you expect to see? (Required)
Consistent.

### 5. What is your migration tool and TiKV version? (Required)
-TiKV: v6.1.0 nightly

### PR DESCRIPTION
**Pull request by haojinming**
### What problem does this PR solve?

Issue Number: close #108 

Problem Description: 
Checksum maybe mismatch if data expired during backup/restore.

### What is changed and how does it work?
1. Add a warning that "Warning: TiKV cluster is TTL enabled, checksum may be mismatch if some data expired during backup/restore."
2. Implement checksum debug command.
3. Add api version check to reject the invalid backup/restore operation.

### Code changes

- Has exported function/method change

### Check List for Tests

This PR has been tested by at least one of the following methods:
- Unit test
- Manual test (add detailed scripts or steps below)

### Side effects

- No side effects

### Related changes

- No related changes

### CODE REVIEW

File: br/pkg/restore/client.go [hunk 1]
```diff
@@ -64,12 +67,17 @@ func NewRestoreClient(
 	keepaliveConf keepalive.ClientParameters,
 	isRawKv bool,
 ) (*Client, error) {
+	apiVerion, err := backup.GetTiKVApiVersion(context.Background(), pdClient, tlsConf)
```
Comment (pingyu) [inline br/pkg/restore/client.go:70]: It's a little strange to use a method from `backup` in restore procedure. It would be better to move `GetTiKVApiVersion` as a common method.

File: br/pkg/task/backup_raw.go [hunk 2]
```diff
@@ -58,10 +58,10 @@ func DefineRawBackupFlags(command *cobra.Command) {
 }
 
 // CalcChecksumFromBackupMeta read the backup meta and return Checksum
-func CalcChecksumFromBackupMeta(ctx context.Context, curAPIVersion kvrpcpb.APIVersion, cfg *Config) (checksum.Checksum, []*utils.KeyRange, error) {
+func CalcChecksumFromBackupMeta(ctx context.Context, curAPIVersion kvrpcpb.APIVersion, cfg *Config) (*backuppb.BackupMeta, checksum.Checksum, []*utils.KeyRange, error) {
```
Comment (pingyu) [inline br/pkg/task/backup_raw.go:61]: Nit: maybe better to get `backupMeta` outside then pass in here. As what "CalcChecksumFromBackupMeta" says.

**Review by pingyu — COMMENTED** [review]
Rest LGTM~

File: br/pkg/restore/client.go (hunk 1 above)
Comment (haojinming) [reply br/pkg/restore/client.go]: moved to common `conn` package, thanks for the good suggestion.

File: br/pkg/task/backup_raw.go (hunk 2 above)
Comment (haojinming) [reply br/pkg/task/backup_raw.go]: done

**Review by pingyu — APPROVED** [review]
LGTM~
