### PR TITLE
[fix #133] Add sort back to pipeline without db sort

### LINKED ISSUE #133: cdc: Add sorter back to pipeline
### 1. Describe the bug

The sorter of pipeline was removed in early cdc [PR](https://github.com/tikv/migration/pull/74/files#diff-571e6402cf7475dcd07a4193de26b908581ff481d6f698a43b9c4ab17af21933).
And that time we thought that as timestamps of entries in a region are always non-decreasing, we don't need the sorter.

But now I find that actually the processor is not processing only one region, but multiple regions at a time. And now the timestamps are not in order. This will make the resolved-ts logic wrong.
See [here](https://github.com/tikv/migration/blob/48c96505cdcca73dceb1aa1476597f62d3661dc6/cdc/cdc/sink/buffer_sink.go#L129):
```go
	keyspanID, resolvedTs := batch[i].keyspanID, batch[i].resolvedTs
	rawKVEntries := b.buffer[keyspanID]

	i := sort.Search(len(rawKVEntries), func(i int) bool {
		return rawKVEntries[i].CRTs > resolvedTs
	})
	if i == 0 {
		continue
	}
	state.metricTotalRows.Add(float64(i))

	err := b.Sink.EmitChangedEvents(ctx, rawKVEntries...)
```

If the CRTs of entries are not in order, we would not get all the expected entries that earlier than `resolvedTs`.

Although we can do a full search here, but it would be inefficiency. As the advancing of `resolvedTs` would be slow, we will scan again and again.

We can implement the sorter using merge sort, to utilize the feature of non-decreasing.

Please also note that, it's possible that we would break the order of entires timestamp in the same region later. See https://github.com/tikv/tikv/issues/12020.

### 5. What is your migration tool and TiKV version? (Required)

- TiKV:
- TiKV CDC:
- TiKV BR:
- TiKV Online Bulk Load:

### PR DESCRIPTION
**Pull request by zeminzhou**
### What problem does this PR solve?
Add sort back to pipeline

Issue Number: fix #133

Problem Description: 
see issue #133

### What is changed and how does it work?
Add sort back to pipeline without db sort.

### Code changes

- Has exported function/method change

### Check List for Tests

This PR has been tested by at least one of the following methods:
- Unit test

### CODE REVIEW

**Review by haojinming — APPROVED** [review]
PR is big, suggest to do some manual testing of cdc process.  Rest LGTM~

File: cdc/cdc/sorter/encoding/key.go [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+import (
+	"encoding/binary"
+
+	"github.com/pingcap/log"
+	"github.com/tikv/migration/cdc/cdc/model"
+	"go.uber.org/zap"
+)
+
+// DecodeKey decodes a key to uniqueID, keyspanID, startTs, CRTs.
+func DecodeKey(key []byte) (uniqueID uint32, keyspanID uint64, startTs, CRTs uint64) {
```
Comment (pingyu) [inline cdc/cdc/sorter/encoding/key.go:25]: These 3 methods seems to be for leveldb sorter. They are useless now.

**Review by pingyu — APPROVED** [review]
LGTM~
