### PR TITLE
[fix #102]Br checksum

### LINKED ISSUE #102: [BR] no checksum in backup/restore process
### 1. Describe the bug
Does not do checksum in back/restore process.

### 2. Minimal reproduce step (Required)
run `tikv-br backup raw` & `tikv-br restore raw`

### 3. What did you see instead (Required)
no checksum is done during back/restore.
### 4. What did you expect to see? (Required)
do checksum in back/restore process and report checksum result.
### 5. What is your migration tool and TiKV version? (Required)

- TiKV BR:

### PR DESCRIPTION
**Pull request by haojinming**
### What problem does this PR solve?

Issue Number: close #102 

Problem Description: 

no checksum is done after backup/restore

### What is changed and how does it work?
1. add checksum package which takes range and pd endpoint as input and do checksum calculation.
2. do checksum after back/restore
3. add checksum progress report as checksum maybe slow. 
### Code changes

- Has exported function/method change

### Check List for Tests

This PR has been tested by at least one of the following methods:
- Unit test
- Manual test (add detailed scripts or steps below)
### Side effects

- Possible performance regression, WHY:  checksum maybe slow, take about 20% time in backu processs and checksum can be disabled with command.
- No side effects

### Related changes

- No related changes

### CODE REVIEW

File: br/pkg/checksum/executor.go [hunk 1]
```diff
@@ -0,0 +1,321 @@
...
+		Algorithm: kvrpcpb.ChecksumAlgorithm_Crc64_Xor,
+		Ranges: []*kvrpcpb.KeyRange{{
+			StartKey: rangeStart,
+			EndKey:   rangeEnd,
+		}},
+	})
+	if err != nil {
+		return errors.Trace(err)
+	}
+	if resp.GetRegionError() != nil {
```
Comment (pingyu) [inline br/pkg/checksum/executor.go:145]: Some errors are inevitable, e.g. `not_leader`. Maybe we can refer to how does `client-go` deal with these errors..

File: br/pkg/checksum/executor.go [hunk 2]
```diff
@@ -0,0 +1,321 @@
...
+			Context:  kvrpcpbCtx,
+			StartKey: curStart,
+			EndKey:   rangeEnd,
+			Cf:       "default",
+			Limit:    MaxScanCntLimit,
+		})
+		if err != nil {
+			return errors.Trace(err)
+		}
+		if resp.GetRegionError() != nil {
```
Comment (pingyu) [inline br/pkg/checksum/executor.go:220]: Ditto.

File: br/pkg/checksum/executor.go [hunk 3]
```diff
@@ -0,0 +1,321 @@
...
+			return errors.New(resp.GetRegionError().String())
+		}
+		iterKvPairs := resp.GetKvs()
+		if !firstLoop { // first is duplicated
```
Comment (pingyu) [inline br/pkg/checksum/executor.go:224]: Use `append(iterKvPairs[kvCnt-1].Key, 0)` as next `curStart`. Then we will not get the last key again.

File: br/pkg/checksum/executor.go [hunk 4]
```diff
@@ -0,0 +1,321 @@
...
+	method StorageChecksumMethod,
+	progressCallBack func(backup.ProgressUnit),
+) (Checksum, error) {
+	// reuse restore split codes, but do nothing with split.
+	splitClient := restore.NewSplitClient(exec.pdClient, nil, true)
+	regionInfos, err := restore.PaginateScanRegion(ctx, splitClient, exec.startKey, exec.endKey, restore.ScanRegionPaginationLimit)
+	if err != nil {
+		return Checksum{}, errors.Trace(err)
+	}
+	// regionInfos maybe duplicated
```
Comment (pingyu) [inline br/pkg/checksum/executor.go:270]: Why ?

File: br/pkg/checksum/executor.go [hunk 5]
```diff
@@ -0,0 +1,321 @@
...
+	finalChecksum := Checksum{}
+	workerPool := utils.NewWorkerPool(exec.concurrency, "Ranges")
+	eg, ectx := errgroup.WithContext(ctx)
+	for _, r := range regionMap {
+		regionInfo := r // copy to another variable in case it's overwritten
+		workerPool.ApplyOnErrorGroup(eg, func() error {
+			elctx := logutil.ContextWithField(ectx, logutil.RedactAny("region-id", regionInfo.Region.Id))
+			var err error
+			if method == StorageChecksumCommand {
+				err = exec.doChecksumOnRegion(elctx, regionInfo, splitClient, &finalChecksum, progressCallBack)
```
Comment (pingyu) [inline br/pkg/checksum/executor.go:284]: Is it thread-safe here ?

File: br/pkg/restore/import.go [hunk 6]
```diff
@@ -366,10 +367,12 @@ func (importer *FileImporter) Import(
 					logutil.ShortError(errDownload))
 				return errors.Trace(errDownload)
 			}
-			log.Debug("download file done", zap.String("file-sample", files[0].Name), zap.Stringer("take", time.Since(start)),
+			log.Info("download file done", zap.String("file-sample", files[0].Name), zap.Stringer("take", time.Since(start)),
 				logutil.Key("start", files[0].StartKey),
 				logutil.Key("end", files[0].EndKey),
+				logutil.Region(info.Region),
 			)
+			downloadSucceed = true
```
Comment (pingyu) [inline br/pkg/restore/import.go:375]: Seems that any successful region will make `downloadSucceed` be true, but we expect it to be "all successful" ?

File: br/pkg/checksum/executor.go (hunk 5 above)
Comment (haojinming) [reply br/pkg/checksum/executor.go:285]: yes, `doChecksumOnRegion` just handle one single region, then update the checksum in a lock.

Comment (pingyu) [reply br/pkg/checksum/executor.go:285]: I mean the thread-safe of `finalChecksum`. It seems that multi threads are modifying it simultaneously.

Comment (haojinming) [reply br/pkg/checksum/executor.go:285]: `doChecksumOnRegion` updates the `finalChecksum` in a lock. Please see: https://github.com/haojinming/migration/blob/15dbfdeb93847fa29b8e617c81fef6fedd97a894/br/pkg/checksum/executor.go#L153-L155

File: br/pkg/checksum/executor.go (hunk 1 above)
Comment (haojinming) [reply br/pkg/checksum/executor.go:205]: Change to use client-go to scan the data. `client-go` now does not support `checksum`, so add retry for region error here. In the future, i think it's better to support checksum in `client-go` and reuse the error handling code.

File: br/pkg/checksum/executor.go (hunk 3 above)
Comment (haojinming) [reply br/pkg/checksum/executor.go]: done

File: br/pkg/checksum/executor.go (hunk 4 above)
Comment (haojinming) [reply br/pkg/checksum/executor.go]: I see this comment in somewhere else, but have not see it again. I add a check deduplicte function `checkDuplicateRegion` to debug the failure if it happens.

**Comment by haojinming** [comment]
@pingyu @ystaticy PTAL~ thanks.

File: br/pkg/task/rawkv_config.go [hunk 7]
```diff
@@ -112,6 +112,9 @@ func (cfg *RawKvConfig) parseDstAPIVersion(flags *pflag.FlagSet) error {
 	if err != nil {
 		return errors.Trace(err)
 	}
+	if len(originalValue) == 0 {
```
Comment (pingyu) [inline br/pkg/task/rawkv_config.go:115]: `dst-api-version` design to default as the same to api version of TiKV.

File: br/pkg/task/restore.go [hunk 8]
```diff
@@ -27,7 +27,7 @@ const (
 	// FlagBatchFlushInterval controls after how long the restore batch would be auto sended.
 	FlagBatchFlushInterval = "batch-flush-interval"
 
-	defaultRestoreConcurrency = 128
+	defaultRestoreConcurrency = 512
```
Comment (pingyu) [inline br/pkg/task/restore.go:30]: `512` is big. Default value would be better to be conservative. To avoid some new users crash their cluster.

File: br/pkg/checksum/executor.go (hunk 1 above)
Comment (pingyu) [reply br/pkg/checksum/executor.go:204]: Yes. Add checksum to client-go would be better.

File: br/pkg/checksum/executor.go [hunk 9]
```diff
@@ -0,0 +1,349 @@
...
+		if len(keys) == 0 || len(keys) < MaxScanCntLimit {
+			break // reach the end
+		}
+		// append '0' to avoid getting the duplicated kv
+		curStart = append(keys[len(keys)-1], '0')
+	}
+	return checksum, nil
+}
+
+func checkDuplicateRegion(ctx context.Context, regionInfos []*restore.RegionInfo) error {
```
[the remark this answers is not in the document]
Comment (haojinming) [reply br/pkg/checksum/executor.go:143]: I check the code in `ScanRegions`, this scenior shoudl not happen. `RegionId` is the unique identifier.

File: br/pkg/checksum/executor_test.go [hunk 10]
```diff
@@ -0,0 +1,70 @@
...
+func (m *mockPdCLient) RawChecksum(ctx context.Context, in *kvrpcpb.RawChecksumRequest, opts ...grpc.CallOption) (*kvrpcpb.RawChecksumResponse, error) {
+	stubChecksum := getStubChecksum()
+	response := kvrpcpb.RawChecksumResponse{}
+	response.Checksum = stubChecksum.Crc64Xor
+	response.TotalKvs = stubChecksum.TotalKvs
+	response.TotalBytes = stubChecksum.TotalBytes
+	return &response, nil
+}
+
+func TestChecksumExecutor(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (haojinming) [reply br/pkg/checksum/executor_test.go:45]: The input parameters are changed and a little difficult to test in unit test. I would like to find the way to test in another commong PR.

File: br/pkg/restore/range.go [hunk 11]
```diff
@@ -34,7 +34,7 @@ func SortRanges(ranges []rtree.Range, rewriteRules *RewriteRules) ([]rtree.Range
 			if startID == endID {
 				rg.StartKey, rule = replacePrefix(rg.StartKey, rewriteRules)
 				if rule == nil {
-					log.Warn("cannot find rewrite rule", logutil.Key("key", rg.StartKey))
+					log.Debug("cannot find rewrite rule", logutil.Key("key", rg.StartKey))
```
[the remark this answers is not in the document]
Comment (haojinming) [reply br/pkg/restore/range.go:37]: Yes，it hit here previously and it's a bug and fixed in commit: https://github.com/tikv/migration/pull/103/commits/47d53156aabebdf1e9d74323aac2c58ffb9ea1be, i will revert this log level change.

File: br/pkg/task/restore.go (hunk 8 above)
Comment (haojinming) [reply br/pkg/task/restore.go:30]: From the testing experience, `512` concurrency is much faster than `128` in restore process. If we keep the default `128` process, i think we should also keep `concurreny` as a visible parameter which is hidden now.https://github.com/tikv/migration/blob/d8c0fb1ba6f5d96dd43d8806c3082e152ef77696/br/pkg/task/common.go#L94

File: br/pkg/checksum/executor.go (hunk 1 above)
Comment (haojinming) [reply br/pkg/checksum/executor.go:204]: emm, if `BR` depend on the latest `client-go`, we need resolve the dependency problem between `grpc` and `etcd` in different versions. I have another branch https://github.com/haojinming/migration/tree/br-checksum-with-client to do this and need upgrade to go1.18 to do this as `BR` depend on `tidb` repos and `tidb` use go1.18 version now. Still have some problem in `go` static check. So I would like to delay this.

File: br/pkg/task/restore.go (hunk 8 above)
Comment (haojinming) [reply br/pkg/task/restore.go:30]: I would like optimize the logic in next pr.

File: br/pkg/task/rawkv_config.go (hunk 7 above)
Comment (haojinming) [reply br/pkg/task/rawkv_config.go:115]: ok, the behaviour is changed. Keep empty valid and adjust the value after the cur api version got.

File: br/pkg/restore/import.go [hunk 12]
```diff
@@ -438,8 +438,9 @@ func (importer *FileImporter) Import(
 				return errors.Trace(errIngest)
 			}
 		}
-		if !downloadSucceed {
-			errMsg := fmt.Sprintf("some files failed to download, %s.", files[0].Name)
+		if downloadRegionCnt == 0 {
+			log.Error("No region downloads the files", logutil.Files(files), zap.Int("count", len(regionInfos)))
+			errMsg := fmt.Sprintf("No region downloads the file: %s.", files[0].Name)
```
Comment (pingyu) [inline br/pkg/restore/import.go:443]: Try `errors.Errorf`

File: br/pkg/utils/key.go [hunk 13]
```diff
@@ -144,8 +145,8 @@ func ConvertBackupConfigKeyRange(startKey, endKey []byte, srcAPIVer, dstAPIVer k
 func EncodeKeyRange(start, end []byte) *KeyRange {
 	keyRange := KeyRange{}
 	keyRange.Start = codec.EncodeBytes(start)
-	if len(end) == 1 && end[0] == APIV2KeyPrefixEnd {
-		keyRange.End = []byte{APIV2KeyPrefixEnd}
+	if len(end) == APIV2KeyPrefixLen && bytes.Equal(end, APIV2KeyPrefixEnd[:]) {
```
Comment (pingyu) [inline br/pkg/utils/key.go:148]: `if bytes.Equal(end, APIV2KeyPrefixEnd[:])` is enough ?

**Review by pingyu — COMMENTED** [review]
Rest LGTM~

File: br/pkg/restore/import.go (hunk 12 above)
Comment (haojinming) [reply br/pkg/restore/import.go]: Done, thanks.

File: br/pkg/utils/key.go (hunk 13 above)
Comment (haojinming) [reply br/pkg/utils/key.go]: yes, fixed. PTAL~

**Review by pingyu — APPROVED** [review]
LGTM~
