### PR TITLE
[close #200] CDC & BR version check with new tag naming style

### LINKED ISSUE #200: BR/CDC version check fails
### 1. Describe the bug
1. CDC [Makefile](https://github.com/tikv/migration/blob/0a4ace4345af6abbc49aab608ada99a4f51c6eb2/cdc/Makefile#L45-L58) does not take real version tag into code.
2. BR run into failure of version check with new tag naming ,like `br-v1.1.0`. 
`Error: running BR in incompatible version of cluster.: br is not in dotted-tri format: invalid version, please recompile using `git fetch origin --tags && make build`: [BR:Common:ErrVersionMismatch]version mismatch`
### 4. What did you expect to see? (Required)
CDC and BR can adapt the new tag naming style.

### 5. What is your migration tool and TiKV version? (Required)

- TiKV CDC:
- TiKV BR:

### PR DESCRIPTION
**Pull request by haojinming**
Signed-off-by: haojinming <jinming.hao@pingcap.com>

### What problem does this PR solve?

Issue Number: close #200 

Problem Description: 

### What is changed and how does it work?
1. New tag naming stype is br-vx.x.x or cdc-vx.x.x, which cause version check issue in BR and CDC
2. Remove `br` or `cdc` prefix before version check.

### Check List for Tests

This PR has been tested by at least one of the following methods:
- Unit test

### Side effects

- No side effects

### Related changes

- No related changes

### CODE REVIEW

File: cdc/pkg/version/check.go [hunk 1]
```diff
@@ -65,6 +65,7 @@ func removeVAndHash(v string) string {
 	}
 	v = versionHash.ReplaceAllLiteralString(v, "")
 	v = strings.TrimSuffix(v, "-dirty")
+	v = strings.TrimPrefix(v, "cdc-") // tag is named with cdc-vx.x.x
```
Comment (zeminzhou) [inline cdc/pkg/version/check.go:68]: Is tikv-cdc better ?

**Review by zeminzhou — APPROVED** [review]

**Review by pingyu — APPROVED** [review]
LGTM~

File: cdc/pkg/version/check.go (hunk 1 above)
Comment (haojinming) [reply cdc/pkg/version/check.go:68]: It depends on the release tag naming style. Now we use `cdc-vx.x.x` and `br-vx.x.x`, which omit the `tikv` prefix.

Comment (zeminzhou) [reply cdc/pkg/version/check.go:68]: Get it.
